### ISSUE TITLE
PhpStorm Run with Tinkerwell not working

### ISSUE THREAD

**Issue by luiz-brandao-jr** [beyondcode/tinkerwell-community#108]
Hello there, when I select `Run with Tinkerwell` in PhpStorm I'm only getting a blank tab. I'm not sure how to start debugging it. Do you have any idea why and suggestions on how to make it work? 

![image](https://user-images.githubusercontent.com/704231/74777435-7a964900-5267-11ea-80d0-747fd8a2a13e.png)

If it helps, I'm running PHP through Vagrant.

Thank you!

**Comment by chqshaitan** [comment]
Hi bud, the way it works is that you highlight whatever php code you want to run in tinker well, then right click and select either open with tinkerbell or run with.

Unfortunately this is as far as i got, as i then getting an error saying that i did not have tinkerwell installed(on ubuntu).

**Comment by Aleksandar-Mitic** [comment]
> Hi bud, the way it works is that you highlight whatever php code you want to run in tinker well, then right click and select either open with tinkerbell or run with.
> 
> Unfortunately this is as far as i got, as i then getting an error saying that i did not have tinkerwell installed(on ubuntu).

Same issue here.

**Comment by richdonne** [comment]
Same issue here - displays nothing, selected code , and nothing, also try to type in the box nothing

**Comment by SchuBu** [comment]
I have the same issue. fresh installed tinkerwell on windows. but the phpstorm integration with the plugin from the marketplace won't work ... please let me know how to fix it. i only see the empty tinkerwell tab in my phpstorm ide.

**Comment by herpaderpaldent** [comment]
seems to be the same issue as #105

**Comment by TheDoctor0** [comment]
I did some digging after decompiling Tinkerwell plugin.

At first I though that it's the same problem with file path as suggested in #105.
But it's not as I checked it with manually added debug messages.

The only rational explanation was that there is something wrong with PHP process output.
After rewriting command output section using ProcessBuilder with redirected error stream I finally got an output: "PHP Warning: 'vcruntime140.dll' 14.0 is not compatible with this PHP build linked with 14.16 in Unknown on line 0".

From here it was clear that it is actually [PHPStorm bug](https://youtrack.jetbrains.com/issue/WI-50733) itself - there is a simple workaround described in linked issue. The bug is already fixed but unfortunately on 2020.2 version branch, not so it's not part of 2020.1 RC.

![phpstorm64_KX6QymR5h7](https://user-images.githubusercontent.com/16612504/79166249-09958c80-7de5-11ea-9cc2-bd545b8f10bd.png)

**Comment by micksp** [comment]
Any update on this? In phpstorm I still see:
`You do not have Tinkerwell installed. Do you want to open the Tinkerwell website?`
And as beautiful as the tinkerwell website is, I don't expect any solution from visiting it...
I am on ubuntu 18.04 with tinkerwell globally available; the appimage is in /opt and usr/local/bin has a symlink. So, what doe phpstorm expect?

**Comment by herpaderpaldent** [comment]
Any update on this? Seems like the website consist of a false promise ... there is no IDE integration apparently for linux users

**Comment by micksp** [comment]
nope, silence is golden but sometimes....

**Comment by sschlein** [comment]
Update: We've hired someone to support us on bugs and new features but it takes some time until this is getting traction. We'll remove the promise about IDE integration on Linux from the website until it works later today.

**Comment by sschlein** [comment]
I have released docs for the plugins here https://beyondco.de/docs/tinkerwell/basic-usage/ide-plugins 

Unfortunately, we are likely not able to provide plugins for Linux and Windows in the same way that the plugins work for macOS. You can find more information about this in the docs.

**Comment by sschlein** [comment]
In case you missed it and are still subscribed to this issue:

We have released a new dedicated Tinkerwell PHPStorm plugin that does not connect to the Tinkerwell app and does work on macOS, Linux and Windows!

Merry Christmas!

**Comment by Aleksandar-Mitic** [comment]
Bravo!

**Comment by micksp** [comment]
Well, it does work. So that's great. I hope there will be 

I hope for some docs to explore the possibilities. 
![image](https://user-images.githubusercontent.com/4571252/103136208-a6bbfb00-46be-11eb-9205-c65cc4df0260.png)
which leads to: 
```
Sorry, the page you are looking for could not be found.
```
