### ISSUE TITLE
Select custom php on SSH

### ISSUE THREAD

**Issue by decadence** [beyondcode/tinkerwell-community#122]
Sometimes we need ability to select which command Tinkerwell should use on the SSH for PHP execution.
Now it's hardcoded to "php" I think but if I need to use different PHP version (command php72 for example) I can't handle it with Tinkerwell.

**Comment by ahmadabuaysheh** [comment]
+1
I tried to use it to test a WordPress instance and failed because the default one was set to 5.6.
I tried also to trick Tinkerwell with an alias but didn't Tinkerwell happened to bypass the trick.

**Comment by jkujawski** [comment]
I'm running into exactly the same issue. My server was configured so that php is actually older version with no libs for mysql, while php72 has everything and nginx actually uses php72 socket, not php.

My suggestion would be to just add  "php" alias in connection configuration :)

**Comment by paul-gene** [comment]
Is there any workaround for this currently? Just encountered this issue today with one of our dev servers.

**Comment by parkershepherd** [comment]
I am unable to use Tinkerwell for SSH because of this. The servers I want to connect to do not have any global `php` binaries, and require `export PATH=/usr/local/php/<version>/bin:$PATH` before being able to run any PHP commands.

a) custom command after SSH connection
b) custom PATH
c) custom PHP binary

Would all resolve this issue, but the SSH connection is not extensible enough to work right now

**Comment by DaftMonk** [comment]
This issue is also preventing me from using Tinkerwell for SSH.

**Comment by paul-gene** [comment]
@mpociot why have you closed this?

**Comment by sschlein** [comment]
https://twitter.com/marcelpociot/status/1277631558753681408
