### ISSUE TITLE
warning when using Auth::login

### ISSUE THREAD

**Issue by micksp** [beyondcode/tinkerwell-community#230]
On logging in a user I get the following warning:
```
$u = User::find(1);
Auth::login($u);
```
Response: 
```
PHP Warning:  unlink(.../storage/framework/sessions/x4LgihfRqiKyCk9f3bNjJjzeApJiNTr8tL6w5Nf4): No such file or directory in .../vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 219
```
I issued a merge request on laravel for checking if a file exists before trying to delete it, but this appears to be an error in the Tinkerwell code. Any thoughts on this?

**Comment by mpociot** [comment]
The same error occurs when running the code through `php artisan tinker`.

After some digging, I found out that this happens because of the way that Laravel handles the session migrations.I suppose this happens because the session was never opened/created in the first place. So Laravel tries to delete a non-existing Session file. Probably only happens in the CLI context
