### ISSUE TITLE
Download previous versions

### ISSUE THREAD

**Issue by fri3ndly** [beyondcode/tinkerwell-community#286]
Is there any way to download previous version of Tinkerwell? I have the latest and it doesn't work on a lot of our 5.8.* projects that cannot be updated to v6 or v7 or yet

**Comment by mpociot** [comment]
Why doesn't it work though? :) 
Which error do you get?

**Comment by fri3ndly** [comment]
I think it's because it's forcing usage of v6 or v7.

I'm just unable to type anything as input - No errors as such.

I just right clicked to run an artisan command and got this:

`PHP Warning:  unlink(/Applications/Tinkerwell.app/Contents/Resources/Laravel/6.0/bootstrap/cache/config.php): No such file or directory in /Applications/Tinkerwell.app/Contents/Resources/Laravel/6.0/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 207`

**Comment by fri3ndly** [comment]
Ok so the cache:clear command worked OK - I may be being an idiot Marcel but I'm sure there used to be a couple of panels, one for input and one for output. I don't seem to have the input screen. I have tried toggling windows in the 'View' toolbar

**Comment by fri3ndly** [comment]
<img width="1121" alt="Screenshot 2020-08-26 at 10 19 58" src="https://user-images.githubusercontent.com/2011395/91285964-bfa2b700-e785-11ea-9a92-bcf49cff49b5.png">

**Comment by njames** [comment]
I hear you @fri3ndly I started saving the downloads *just in case*

It will default to 7 but if you change your local directory to one of you 5.8 apps it will work from that instance. 

Happy days.

**Comment by sschlein** [comment]
Hey, you can create some local folders for older versions and use them for tinkering with these versions.

We are going to ship only the latest Laravel version as default project in future versions as all the small files from different versions (incl. vendor folder) create issues during the install and update process. We'll make sure to ship this with a custom default folder so that you can point Tinkerwell to a local folder that gets opened on app-start instead of using the default project that we ship with the app.

**Comment by fri3ndly** [comment]
> Hey, you can create some local folders for older versions and use them for tinkering with these versions.
> 
> We are going to ship only the latest Laravel version as default project in future versions as all the small files from different versions (incl. vendor folder) create issues during the install and update process. We'll make sure to ship this with a custom default folder so that you can point Tinkerwell to a local folder that gets opened on app-start instead of using the default project that we ship with the app.

Thanks sschlein. I know what you're saying and in theory that should work but I'm definitely encountering issues that weren't apparent in previous version of Tinkerwell. I can't get the most simple of requests to work in HTTP mode (as above with bcrypt) but also here just listing what should be a simple array:

I'm having to keep using tinker or tinx at the moment which is a shame since I have a tinkerwell licence but the previous few versions don't seem to work correctly. I have gone back as far as 2.7.0 which seems a bit less broken but then forces an update to the latest version anyway so difficult to test with.

**Comment by sschlein** [comment]
This is really weird! I'm also running Catalina and tested a 5.6 project with PHP 7.2 and it works for me. I'm not sure how to debug your environment to track down the issue. If this is local, my number one recommendation is to select your local PHP binary again 🙈

You can always download older versions by changing the URL to the download to an older version number. We are going to release new versions of all our apps in the next weeks that address a few issues and add new features. On top of my list is the possibility to disable the automated updater so that you can keep a version if you have issue with a newer one. I also want to make older versions available for download via the dashboard.

**Comment by fri3ndly** [comment]
Thanks for the reply sschlein.

I got Tinkerwell working yesterday somehow and now it's back to it's usual behaviour and showing the blank pages with '1' for results etc as above.

I have tried downloading 2.0.0 but none of the links work. Any idea what the link should be?

I've tried:

URL/Tinkerwell-2.0.0.dmg
URL/Tinkerwell-2.0.dmg
URL/Tinkerwell-2.dmg

None of which are valid URL's and result in:

```
<Error>
<Code>AccessDenied</Code>
<BucketName>tinkerwell</BucketName>
<RequestId>tx0000000000000966edd38-005f525c46-2afb529-fra1a</RequestId>
<HostId>2afb529-fra1a-fra1</HostId>
</Error>
```

Thanks

**Comment by sschlein** [comment]
I think you tested the only ones that did not work.

A good indicator are the release notes: 
https://beyondco.de/docs/tinkerwell/releases/2-8-5
https://tinkerwell.app/releases

URL/Tinkerwell-2.6.0.dmg
URL/Tinkerwell-2.7.0.dmg
URL/Tinkerwell-2.8.0.dmg
etc.

We are ging to add an area for older version soon.
