### ISSUE TITLE
Error on unit test laravel 8

### ISSUE THREAD

**Issue by ElRochito** [beyondcode/tinkerwell-community#297]
Hi,

I've upgrade Tinkerwell to 2.9.0 and when I launch unit test I've got this :

`PHP Notice:  Undefined index: extensions in <path>/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 1065`

Test was not executed

Thanks for your help

**Comment by joshhanley** [comment]
Just to confirm, I am seeing the same thing when changing Tinker Mode to testing on Laravel 89 default installation:

```
PHP Notice:  Undefined index: extensions in /Applications/Tinkerwell.app/Contents/Resources/Laravel/8.0/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 1065
```

This is only happening for applications running PHPUnit 9. 
It also happens when I change to a Laravel 7 app running PHPUnit 9.

But it works fine when you select Laravel 7 default.

@mpociot FYI - this is happening after upgrade to 2.9.0

**Comment by mpociot** [comment]
This is now fixed and I'll tag it in a new release later

**Comment by joshhanley** [comment]
Thanks Marcel! 🙂
