### ISSUE TITLE
Run lines independently

### ISSUE THREAD

**Issue by minthemiddle** [beyondcode/tinkerwell-community#30]
Right now if you have several lines of code, Tinkerwell will run all of them when you execute. 
However, there are situations where you only want to run single lines (re-run certain lines, but not others) without having to delete specific lines first.

For example when testing the schedule runner manually, you might create a model first and do certain things after repetedly. Right now you have to prepare everything together and run all lines at once.

```php
$user = factory(User::class)->create();
$timelapse = now()->addDay(1);
Artisan::call('schedule:run');
$timelapse = now()->addDay(1);
Artisan::call('schedule:run');
```

It would be nice if I could select/right-click a line and just execute it/from it.

Here's an inspiration from JupyterNotebook that has similar functionality:

![image](https://user-images.githubusercontent.com/1950766/69351368-8039be00-0c7b-11ea-99ae-fe7f3399d86a.png)

**Comment by repat** [comment]
![image](https://user-images.githubusercontent.com/516807/69371829-467fac00-0ca9-11ea-8a03-30c0daface38.png)

SequelPro has this too, +1

**Comment by mpociot** [comment]
@minthemiddle The problem with this approach is that we can't store the state of the lines above - like there could be complex objects that are unserializable.
So in order to run code from a specific line, you would still need to run all of the code.

I was working on something similar that would show you the line-by-line output.

![tinkerwell_line_by_line](https://user-images.githubusercontent.com/804684/69421270-e75d7e00-0d20-11ea-9b22-fa728ee02cbd.gif)

**Comment by minthemiddle** [comment]
Line by line would already solve 80% of the use cases

**Comment by marijnbent** [comment]
> @minthemiddle The problem with this approach is that we can't store the state of the lines above - like there could be complex objects that are unserializable.
> So in order to run code from a specific line, you would still need to run all of the code.
> 
> I was working on something similar that would show you the line-by-line output.
> 
> ![tinkerwell_line_by_line](https://user-images.githubusercontent.com/804684/69421270-e75d7e00-0d20-11ea-9b22-fa728ee02cbd.gif)

In your gif I'm noticing that errors continue indefinitely.  Are there plans to use multiple lines for one line to show everything without the need to scroll horizontally?

**Comment by jbraband** [comment]
In Microsoft SQL Management Studio and mySQL WorkBench you can execute the whole document, or the selected portion. 

i prefer SQL Management Studio's approach for the keyboard shortcut since it is combined. If there is a selection, only the selected code executes. If there is no selection, then the whole document executes.

This would make my muscle memory useful in Tinkerwell :)

**Comment by mpociot** [comment]
I'm closing this for now. We already have the ability to run only selected code using CMD+Shift+R. Maybe we will add a line-by-line feature in the future.
