### ISSUE TITLE
tabs sometimes go missing

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#407]
Sometime (and I cant pin it down why) my tabs go missing. I use the `Add Tab` menu and I get a new tab with no tabs. 

Would it be possible to add either / both a 
1. ctrl-tab type shortcut to cycle the tabs (like a browser)
2. a menu option with all windows / tabs open so you can navigate by a menu? 

No rush ... just  a feature request from an appreciative user.

**Comment by sschlein** [comment]
I've only tested switching tabs with shortcuts on Mac but it works by using CMD+1 (+2, +3) so I assume it also works with CTRL+1, etc on Windows.

**Comment by mpociot** [comment]
You can already switch tabs by pressing CTRL+Tab, as well as using CTRL+1,2,3...

We aren't able to reproduce the issue and you seem to be the only one that has this issue. It should be fixed by restarting the application.
If you/we find a reliable way to reproduce the issue, we'll re-open this issue.

**Comment by njames** [comment]
The shortcuts are not reliable on Ubuntu and none of these shortcuts work for me 
CTRL+Tab, as well as using CTRL+1,2,3...
(along with ctlr+t and a few others) 

So seems like you have the shortcuts :+1: but they don't work for me :(

I found out that hitting the share button when they go walkabout (ie missing) they comeback

Next time I find it happening I will do a video for you :movie_camera:
