### ISSUE TITLE
Support php custom connections

### ISSUE THREAD

**Issue by mathieutu** [beyondcode/tinkerwell-community#46]
Hi, 
Locally I use docker containers to handle my projects (see #2), and for stagging I use heroku. 

I can't ssh in both, I use two command lines `docker exec` and  `heroku run`, so I sadly can't use Tinkerwell in my projects.

As said in https://github.com/beyondcode/tinkerwell-suggestions/issues/2#issuecomment-557073707, it would be awesome to have a agnostic mean of connecting tinkerwell to an app. It could be a command line to launch in a project, which starts a "tunnel" or something like that, or a way to precise how to run the php instance (and so the tinker queries).

This issue is so a request for a more generic way to handle connections, and this should resolve all docker, VM, clouds, etc. issues.

Happy to exchange more about that.

Thanks.
Matt'

**Comment by mengidd** [comment]
Yes, please 👆

We exclusively use docker as dev environments, would be super nice to have docker support.

**Comment by dsisean** [comment]
> Hi,
> Locally I use docker containers to handle my projects (see #2), and for stagging I use heroku.
> 
> I can't ssh in both, I use two command lines `docker exec` and `heroku run`, so I sadly can't use Tinkerwell in my projects.
> 


I was able to use Tinkerwell with my local docker environment  by running an sshd service in my application container and exposing port 22.   It sounds like that might not be an option for you, but just thought I'd mention that tinkerwell does work fine with local docker environments that are running sshd.  I happy to provide more details on that if anyone is curious about getting tinkerwell working with a local docker environment (assuming you're able to modify your Dockerfile and/or add a separate SSH service in your compose file)

**Comment by SaundersB** [comment]
@dsisean Could you share how you did so please?

**Comment by nickpoulos** [comment]
@dsisean I am also interested in the details of how you managed that. @SaundersB I believe this is on the right track though: https://docs.docker.com/engine/examples/running_ssh_service/

**Comment by dsisean** [comment]
@SaundersB Sorry I've been a little backed up with work and completely forgot to respond.  I'll try to lay it out in detail for you when I get some time tonight.    The link that @nickpoulos referenced should work if you're able to add additional services to your compose project.  I almost went that route, but wound up just running an ssh service in my main app container and starting the service from a supervisor config file.  I'll follow up later with a detailed layout of my docker/tinkerwell setup.

**Comment by simensen** [comment]
Would be great to get some additional feedback on this, as I've run into some issues with this myself. It *is* working now, but whoah is it a pain.

The biggest issue I discovered was getting the environment variables working correctly. The variables assigned in docker-compose.yml don't exist when someone SSH's into the container. So, if you're relying on environment variables like DB host name that are *different* in your Docker environment than in your `.env` (was the case for me), when Tinkerwell connects, you'll only be able to use the content of your `.env` and that broke a bunch of stuff for me.

My first attempt was to update the Dockerfile to write the environment variables to `/etc/profile` as shown on some places. That worked for full login shells like an SSH from a standard terminal. Bash/etc would load up /etc/profile no problem, but the Tinkerwell connection doesn't work like that... it is actually running the commands one at a time (from what I can tell) instead of opening a persistent SSH connection.

After looking around for a bit, I discovered variables placed in /etc/environment are *always* available, even to non-login shells. Was a hack, but hey, it works.

```
RUN echo "DB_HOST=db" >> /etc/environment \
  && echo "DB_USERNAME=dbuser" >> /etc/environment \
  && echo "DB_PASSWORD=password" >> /etc/environment \
  && echo "LEGACY_DB_HOST=host.docker.internal" >> /etc/environment
```

After that, I was able to get Tinkerwell working and was able to run commands from my own terminal remotely without needing to do a full login shell:

```
> ssh root@localhost -p 4022 env | grep LEGACY
LEGACY_CDS_DB_HOST=host.docker.internal
```

So, assuming you setup ssh server like the article listed above (what I used this morning to get this started), you might have to do some additional work to set any variables that need to be set that are different running under Docker than running locally.

**Comment by dsisean** [comment]
I initially attempted to setup a separate ssh service via the referenced article https://docs.docker.com/engine/examples/running_ssh_service/ .  However, I ran into a bunch of problems similar to what @simensen experienced.

Since time was a factor, instead of wrestling with that, I just ran an SSH service in my main app/PHP container.  That service is then started via my supervisord.conf file.  My docker environment files are setup as follows:

docker-compose.yml
`version: '3.6'
services:
  app:
    build:
      context: .
      args:
        APPDOMAIN: ${APP_DOMAIN}
        APPWEBROOT: ${APP_WEB_ROOT}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${HTTP_PORT}:8080
      - ${SSH_PORT}:22
    environment:
      - DOCUMENT_ROOT=/app/public
      - SKIP_LOCKDOWN_DOCUMENT_ROOT=true
      - OPCACHE_SAVE_COMMENTS=1
      - OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}

# Define your other services here
`

Dockerfile:
`FROM gcr.io/google-appengine/php72:latest

ARG COMPOSER_FLAGS='--prefer-dist --ignore-platform-reqs --optimize-autoloader'
ARG APPDOMAIN
ARG APPWEBROOT
ARG sshhome=/home/sshuser
ENV COMPOSER_FLAGS=${COMPOSER_FLAGS}
ENV DOCUMENT_ROOT=/app/public
ENV PHP_CONFIG_TEMPLATE=/opt/php-configs
ENV PHP_CLI_TEMPLATE=/opt/php72/lib

#add software-properties-common to enable usage of the add-apt-repository command
RUN apt-get update -y \
&& apt-get install -y \
openssh-server -y

#Create single user for SSH access
RUN mkdir /var/run/sshd
RUN groupadd sshgroup && useradd -ms /bin/bash -g sshgroup sshuser

#Copy Public key to container
RUN mkdir $sshhome/.ssh
COPY /data/ssh/id_rsa.pub $sshhome/.ssh/authorized_keys
RUN chown sshuser:sshgroup $sshhome/.ssh/authorized_keys && \
    chmod 600 $sshhome/.ssh/authorized_keys

#Add the ppa:ondrej/php and nginx-mainline repos to provide access to the php7.*-bcmath extension
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/nginx-mainline

#Install PHP extensions and run the composer install script
RUN apt-get update -y \
&& apt-get install -y \
unzip \
autoconf \
php7.2-gd \
#php7.2-bcmath \
build-essential \
libmpdec-dev \
libpq-dev \
&& pecl install decimal \
&& chown -R www-data.www-data $APP_DIR \
&& /build-scripts/composer.sh;

#provide custom php.ini to enable decimal, bcmath and any other necessary PHP modules
COPY php.ini "${PHP_CLI_TEMPLATE}/conf.d"
COPY /data/nginx/ "/etc/nginx/templates/"
COPY supervisord.conf "/etc/supervisor/supervisord.conf"

#Copy the appropriate NGINX template into the container
# Then build the NGINX config file by substituting the appropriate ENV variables
RUN if [ "x${APPDOMAIN}" = "xlocalhost" ] ; then cp "/etc/nginx/templates/app-local.conf.temp" "/etc/nginx/conf.d/nginx-http.conf.temp" ; else cp /etc/nginx/templates/app-ssl.conf.temp "/etc/nginx/conf.d/nginx-http.conf.temp" ; fi \
&& envsubst '$${APPDOMAIN} $${APPWEBROOT}' < "/etc/nginx/conf.d/nginx-http.conf.temp" > "/etc/nginx/conf.d/nginx-http.conf"

RUN chgrp www-data /opt/php72/lib/conf.d/* \
&& chgrp www-data /etc/supervisor/supervisord.conf
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
`

supervisord.conf
`[supervisord]
nodaemon = true
logfile = /dev/null
logfile_maxbytes = 0
pidfile = /var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D

[program:php-fpm]
command = /opt/php/sbin/php-fpm -y /opt/php/etc/php-fpm.conf
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
user = root
autostart = true
autorestart = true
priority = 1000

[program:nginx]
command = /usr/sbin/nginx
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
user = root
autostart = true
autorestart = true
priority = 2000

[include]
files = /etc/supervisor/conf.d/*.conf`

Doing it this way, each time `docker-compose up` is run the SSH service is started in the supervisord.conf.  I'm then able to connect tinkerwell to localhost and whatever port you define for the ${SSH_PORT} variable (in my case this is defined in a separate .env file).  I've been using Tinkerwell with docker on a daily basis with this setup and haven't run into any issues yet (I'll report back if I do).  

Let me know if you need clarification or try the above setup and have trouble.  Happy to help where I can.

**Comment by iraklisg** [comment]
@dsisean Thank you for the detailed instructions, they helped my to successfully  connect tinkerwell to my dockerized app.

However I am still trying to find a way establish a connection using a dedicated ssh service in my `docker-compose.override.yml` file... Any help is most welcome

**Comment by iraklisg** [comment]
For anyone who might be interested, I was finally able to connect tinkerwell to my dockerized Laravel application using a dedicated service.

The steps I followed were the following:

1) Create a Dockerfile that comprises both `php-fpm` and `sshd`
```
FROM ubuntu:18.04

ARG PHP_VERSION=7.4

#
#--------------------------------------------------------------------------
# APT Dependencies Installation
#--------------------------------------------------------------------------
#

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
        curl \
        zip \
        unzip \
        git \
        software-properties-common \
        supervisor \
        locales \
        openssh-server \
    && locale-gen el_GR.UTF-8 # generate and set the correct locales for the application to work properly (dompdf, etc...)

# Boilerplate required by ppa:ondrej/php repositiry
ENV LANG=el_GR.UTF-8 \
    LANGUAGE=el_GR:el \
    LC_ALL=el_GR.UTF-8

# Avoiding user interaction with tzdata when installing php
# see https://askubuntu.com/q/909277/751299
ENV DEBIAN_FRONTEND=noninteractive


#
#--------------------------------------------------------------------------
# PHP Installation
#--------------------------------------------------------------------------
#

ENV PHP_VERSION=$PHP_VERSION

RUN add-apt-repository -y ppa:ondrej/php \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
    php${PHP_VERSION} \
    php${PHP_VERSION}-fpm \
    php${PHP_VERSION}-cli \
    php${PHP_VERSION}-gd \
    php${PHP_VERSION}-mysql \
    php${PHP_VERSION}-imap \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-xml \
    php${PHP_VERSION}-curl \
    php${PHP_VERSION}-ldap \
    php${PHP_VERSION}-zip \
    php-memcached

#
#--------------------------------------------------------------------------
# PHP-FPM Configuration
#--------------------------------------------------------------------------
#

# Overwrite the php-fpm default configuration to run in foreground and forward errors to stderr
RUN mkdir /run/php

COPY ./docker/sshd/php-fpm.conf /etc/php/${PHP_VERSION}/fpm/php-fpm.conf

#
#--------------------------------------------------------------------------
# SSH Configuration
#--------------------------------------------------------------------------
#

ARG SSH_HOME=/home/sshuser/.ssh
ARG SSH_USER=sshuser
ARG SSH_GROUP=sshgroup
ARG SSH_PUBLIC_KEY_PATH

# Create single user for ssh access
RUN mkdir -p /var/run/sshd \
    && groupadd ${SSH_GROUP} \
    && useradd -ms /bin/bash -g ${SSH_GROUP} ${SSH_USER}

# Setup SSH Keys
RUN mkdir -p ${SSH_HOME}
COPY ${SSH_PUBLIC_KEY_PATH} ${SSH_HOME}/authorized_keys
RUN chown ${SSH_USER}:${SSH_GROUP} ${SSH_HOME}/authorized_keys \
    && chmod 600 ${SSH_HOME}/authorized_keys

#
#--------------------------------------------------------------------------
# Supervisor Configuration
#--------------------------------------------------------------------------
#

# Overwirte the supervisor default configuration to tell him how to run nginx and php-fpm
COPY ./docker/sshd/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#

# Clean up installation artifacts to make image leaner
RUN apt-get remove -y --purge software-properties-common \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/html

# Start the container with the following command
CMD ["/usr/bin/supervisord"]

```

2) Create the `supervisor.conf` configuration file

```
; ------------------------------------------------------------------------------------------
; This sets supervisord to run in the foreground (required by Docker to run it).
;
; We then run Nginx and PHP-FPM, making sure to set log files to be coming from stderr/stdout
; (and ensuring Supervisord doesn't attempt to "rotate" log files for these streams of text).
; ------------------------------------------------------------------------------------------

[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D

[program:php-fpm]
command=php-fpm7.4
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

```

3) Add the new `sshd` service to `docker-compose.yml` file

```
 ...

  # ---------------------------------------------------------------------------
  # SSHD Service
  # ---------------------------------------------------------------------------
  #
  sshd:
    image: my_repo/sshd:0.1.0
    build:
      context: ./
      dockerfile: docker/sshd/Dockerfile
      args:
        - SSH_PUBLIC_KEY_PATH=${SSH_PUBLIC_KEY_PATH}
    volumes:
      - .:/var/www/html
    ports:
      - ${SSH_PORT}:22
    networks:
      - backend-dev
  ...
```

4) Add the required build-time arguments to the `.env` file
```
SSH_PORT=2222
SSH_PUBLIC_KEY_PATH=./my/path/to/id_rsa.pub
``` 

Then build the new `my_repo/sshd:0.1.0`  and start the `sshd` service by running: 
```
          docker-compose run \
              -w /var/www/html \
              --detach \
              --service-ports \
              sshd
```
Finally, by having the `sshd` service running you can connect your tinkerwell app by using the exposed port 2222, the ssh user created in Dockerfile (in our example `sshuser`) and setting the app folder to the workdir (in our example `/var/www/html`) as shown below:

![yay](https://user-images.githubusercontent.com/3668360/73532988-7a541c00-4426-11ea-8db3-489c35c0c43f.png)

**Comment by sschlein** [comment]
Can I post this in the tutorials section of the tinkerwell website and link to your github or twitter account for reference?

**Comment by mrwilde-ixa** [comment]
@iraklisg awesome guide there but I think you may have missed what you added to the php-fpm.conf file. It is referenced in the Dockerfile but there is no outline to what you have added in your version.

**Comment by mathieutu** [comment]
Hi. 
Thanks for the tutorial, but could we now keep this issue clean please? 

This is not really about ssh installation in docker, but providing custom php connections in Tinkerwell.

**Comment by tjespers** [comment]
Today i toyed around with the possibility of having the PHP connection settings be customisable & extendable in a similar way as we can already implement custom tinkerwell drivers. As a result of that i decided to share my take on things here to see if this is something that might be deemed useful to others as well.

What i was looking for is a custom connection on a per project basis as all my projects use different docker / docker-compose stacks & containers. As an experiment i've created a simple bash proxy which routes all tinkerwell calls to a custom PHP connection based on the presence of a `.tinkerwell/cli.interpreter` file in my project, 

Code & examples can be found at [tjespers/tinkerwell-interpreters](https://github.com/tjespers/tinkerwell-interpreters)

**Comment by xyNNN** [comment]
What's about this requested feature? It's planned to support custom connections or do we use some presented workaround? Thanks by the way.

**Comment by mpociot** [comment]
Official Docker support is coming to the next version of Tinkerwell. If you need an additional way of connecting Tinkerwell to your application, please open a new issue (depending on the number of requests we might add it) or use one of the existing workarounds from this thread.

**Comment by mathieutu** [comment]
@mpociot Actually this issue was not about handling docker container, but providing a way of using custom php connection, aka let us use a custom command line to launch php.
