### ISSUE TITLE
Background update

### ISSUE THREAD

**Issue by jenky** [beyondcode/tinkerwell-community#464]
I would love to see the update running in background like the old version or at least we can hide the dialog because the new download progress modal is blocking the app and make it completely unusable. Sometimes when the download is slow, it's really frustrating.

**Comment by sschlein** [comment]
We are battling with the updater since the first version and believe that it is more important to update the app without going to the website and downloading a new version. This is why we don't think that we are going to implement a background update again, at least not in the near future.

You can skip an update if you want to use the app and update later.

Can you please tell me where you are from? We are moving the updater files to a CDN to improve the speed, currently, the updates are served from Germany and if you are on the other side of the world, it is a pain that we're going to address.

**Comment by jenky** [comment]
I'm from Vietnam and sometimes the update got stuck and the progress stop. I had to retry several times to complete the update and my network connection is not that bad.

There should be option to hide/minimise the update progress dialog instead of blocking the whole app

**Comment by njames** [comment]
May or may not be related to this but since the fancy updater screen popped up for updating it downloaded in the background, got to the restart and told me I didn't need to do anything so I waited and restarted again and it told me I need to download the new version realised it already had restarted but still didn't update. 

I went back to the website and downloaded again. 

I just don't think the auto update works with AppImage. :(

So I am happy to download manually. 

Thanks for all you do. Tinkerwell is awesome.

**Comment by mpociot** [comment]
@njames I'm unfortunately unable to reproduce this. On Ubuntu, I'm using the AppImageLauncher, which seems to take care of updating too?
Anyway, snap unfortunately doesn't play well with the Electorn updater that we use, so I don't think I can do much more about it.
