### ISSUE TITLE
[Bug]: Shortcut for switching tabs not working and ctrl + t misbehaving on Linux

### ISSUE THREAD

**Issue by Corben78** [beyondcode/tinkerwell-community#484]
### Operating system

Ubuntu 20.04 LTS

### Laravel Version

v8.47.0

### PHP Version

PHP 7.4.3 (cli) (built: Jul  5 2021 15:13:35) ( NTS )

### Project Location

Local

### Bug description

Refering to #467:

Though now the shortcut for quitting the app on Linux via ctrl + q does work again, the shortcut ctrl + page up and ctrl + page down to swap between tabs doesn't work anymore.

Also the shortcut ctrl + t does now two things: it swaps the two characters underneath the cursor, but it also opens a new tab and switches to it (and so the swapping chars change in the previous tab is not really visible unless you go back to that tab).
Though ctrl + t does open new tabs in e.g. a browser, maybe for tinkerwell a shortcut for opening a new tab should be ctrl + n, and ctrl + t should only do the swapping chars action.

### Steps to reproduce

Open several tabs and press ctrl + page up or ctrl + page down.

Enter text, place the cursor between to chars and press ctrl + t.

**Comment by mechelon** [comment]
Thank you for pointing this out. The swapping of characters with ctrl + t is coming from Codemirror which behaviour is based on emacs. I disabled this for Linux because with the combination of opening a new tab it's quite useless.
Are you sure about switching tabs with ctrl + page/down? This wasn't implemented so far so I assume this was kind of a Linux default behaviour. Nevertheless I implemented this for the sake of habit.
Will be available in the next release.
