### ISSUE TITLE
[Feature Request]: Global Custom Driver

### ISSUE THREAD

**Issue by seb-jones** [beyondcode/tinkerwell-community#533]
### Feature Description

I started a [discussion](https://github.com/beyondcode/tinkerwell-community/discussions/531) about this a while back, but it didn't go anywhere, so I figured I'd make a feature request :)

Basically, I think it would be useful if we could specify [custom drivers](https://beyondco.de/docs/tinkerwell/extending-tinkerwell/custom-drivers) that apply globally, rather than per-project. Perhaps these could be stored in sub-directory of the home directory, for example `~/.tinkerwell`.

**Comment by sschlein** [comment]
Hey – we've moved all feature requests to the discussions tab so that there are only issues in the issues tab :)

This feature is definitely useful and we're going to talk about the effort for this internally to see if we can build that. We're currently restructuring our internal roadmap and ways to work, so I can't give you and ETA for this feature

**Comment by seb-jones** [comment]
Cool cool, thanks for letting me know! :+1:
